unit uFunctions;

interface

uses
  Winapi.Windows,        // Windows API functions
  Winapi.TlHelp32,       // Tool help functions for process enumeration
  System.SysUtils,       // System utilities
  System.Classes,        // Base classes
  Vcl.Graphics,          // Graphics operations
  Vcl.ComCtrls,          // Common controls
  Vcl.Controls;          // VCL controls

// Utility function declarations

//Adds a 0 if the lower then 10
function FixNum( I: Integer): String;

// Splits a string at the first occurrence of a symbol and returns the left part
function SplitIt( var sInput: String; sSymble: String ): String; //~R101

// Extracts text between two substrings
function SeporateC( InStr, SubS1, SubS2: String ): string;

// Extracts the file type from a string (gets extension after last dot)
function ExtractType( InString: String ): String;

// Finds and extracts category information from a string list
function ExtractCategory(LookFor: String; LookIn:TStringlist): String;

// Converts decimal separators from dots to commas (for non-English locales)
function NotEnglish( Input: String ): String;

// Converts decimal separators from commas to dots (for KX format compatibility)
function Fix( Input: String ): String;

// Extracts a bitmap from an image list at the specified index
function ExtractBMP( ImageList: TImageList; index:Integer ): TBitmap;

// Checks if a process is currently running
function IsProcessActive(ProcessName: string): Boolean;

// Converts a map ID to its corresponding map name
function IdToMap( ID: Integer ): String;

implementation

function FixNum( I: Integer): String;
begin
  Result := I.ToString;
  if I > 9 then Exit;
  if I <=9 then Result := '0' + I.ToString;
end;

// Splits a string at the first occurrence of a symbol and returns the left part
// Modifies the input string to remove the processed part
function SplitIt( var sInput: String; sSymble: String ): String; //~R101
begin
  if sInput = '' then exit;
  Result := Copy( sInput, 1, Pos(sSymble, sInput) -1 );
  Delete( sInput, 1, Pos(sSymble, sInput) + Length(sSymble) - 1 );
end;

// Extracts text between two substrings
// Returns the text between SubS1 and SubS2 in the input string
function SeporateC( InStr, SubS1, SubS2: String ): string;
begin
  Result := Copy( InStr, Pos(SubS1, InStr) + Length(SubS1), Length(InStr) );
  Result := Copy( Result, 1, Pos(SubS2,Result) - 1 );
  if Length(Result) = 0 then Result := '';
end;

// Extracts the file type from a string (gets extension after last dot)
// Used to get the file extension from XML type attributes
function ExtractType( InString: String ): String;
begin
  Result := SeporateC( InString, 'type="', '"' );;
  for var I := Length(Result) downto 0 do
    if Result[I] = '.' then
    begin
      Result := Copy( Result, I + 1, Length(Result));
      Break;
    end;
end;

// Finds and extracts category information from a string list
// Searches for a matching type and returns the display name
function ExtractCategory(LookFor: String; LookIn:TStringlist): String;
begin
  for var I := 0 to LookIn.Count -1 do
    if Pos( LowerCase(ExtractType(LookFor) + '"'), LowerCase(LookIn.Strings[i]) ) > 0 then
      Result := SeporateC( LowerCase(LookIn.Strings[i]), 'displayname="', '"'  );
end;

// Converts decimal separators from dots to commas (for non-English locales)
// Handles locale-specific decimal formatting issues
function NotEnglish( Input: String ): String;
begin
  Input := StringReplace( Input, '.',',', [rfReplaceAll, rfIgnoreCase] );
  Input := StringReplace( Input, ' ','', [rfReplaceAll, rfIgnoreCase] );
  Result := Input;
end;

// Converts decimal separators from commas to dots (for KX format compatibility)
// Ensures KX format uses dots as decimal separators
function Fix( Input: String ): String;
begin
  Input := StringReplace( Input, ',','.', [rfReplaceAll, rfIgnoreCase] );
  Input := StringReplace( Input, ' ','', [rfReplaceAll, rfIgnoreCase] );
  Result := Input;
end;

// Extracts a bitmap from an image list at the specified index
// Creates a new bitmap and copies the image from the image list
function ExtractBMP( ImageList: TImageList; index:Integer ): TBitmap;
begin
  Result := TBitmap.Create;
  ImageList.GetBitmap( index, Result );
end;

// Checks if a process is currently running
// Uses Windows Tool Help API to enumerate processes
function IsProcessActive(ProcessName: string): Boolean; // uses TlHelp32
var
  SnapShot: THandle;
  Proc: PROCESSENTRY32;
begin
  Result := False;
  SnapShot := CreateToolHelp32Snapshot(TH32CS_SNAPPROCESS, 0);
  Proc.dwSize := SizeOf(PROCESSENTRY32);
  if Process32First(SnapShot, Proc) then
    repeat
      if LowerCase(ProcessName) <> LowerCase(Proc.szExeFile) then Continue;
      Result := True;
      Break;
    until (Process32Next(SnapShot, Proc) = False);
  CloseHandle(SnapShot);
end;

// Converts a map ID to its corresponding map name
// Returns the human-readable name for Guild Wars 2 maps
function IdToMap( ID: Integer ): String;
begin
  Result := 'NVM';  // Default for unknown maps
  case ID of
    15:  Result := 'Queensdale';
    17:  Result := 'Harathi Hinterlands';
    18:  Result := 'Divinity''s Reach';
    19:  Result := 'Plains of Ashford';
    20:  Result := 'Blazeridge Steppes';
    21:  Result := 'Fields of Ruin';
    22:  Result := 'Fireheart Rise';
    23:  Result := 'Kessex Hills';
    24:  Result := 'Gendarran Fields';
    25:  Result := 'Iron Marches';
    26:  Result := 'Dredgehaunt Cliffs';
    27:  Result := 'Lornar''s Pass';
    28:  Result := 'Wayfarer Foothills';
    29:  Result := 'Timberline Falls';
    30:  Result := 'Frostgorge Sound';
    31:  Result := 'Snowden Drifts';
    32:  Result := 'Diessa Plateau';
    33:  Result := 'Ascalonian Catacombs';
    34:  Result := 'Caledon Forest';
    35:  Result := 'Metrica Province';
    36:  Result := 'Ascalonian Catacombs';
    37:  Result := 'Arson at the Orphanage';
    38:  Result := 'Eternal Battlegrounds';
    39:  Result := 'Mount Maelstrom';
    50:  Result := 'Lion''s Arch';
    51:  Result := 'Straits of Devastation';
    53:  Result := 'Sparkfly Fen';
    54:  Result := 'Brisban Wildlands';
    55:  Result := 'The Hospital in Jeopardy';
    61:  Result := 'Infiltration';
    62:  Result := 'Cursed Shore';
    63:  Result := 'Sorrow''s Embrace';
    64:  Result := 'Sorrow''s Embrace';
    65:  Result := 'Malchor''s Leap';
    66:  Result := 'Citadel of Flame';
    67:  Result := 'Twilight Arbor';
    68:  Result := 'Twilight Arbor';
    69:  Result := 'Citadel of Flame';
    70:  Result := 'Honor of the Waves';
    71:  Result := 'Honor of the Waves';
    73:  Result := 'Bloodtide Coast';
    75:  Result := 'Caudecus''s Manor';
    76:  Result := 'Caudecus''s Manor';
    77:  Result := 'Search the Premises';
    79:  Result := 'The Informant';
    80:  Result := 'A Society Function';
    81:  Result := 'Crucible of Eternity';
    82:  Result := 'Crucible of Eternity';
    89:  Result := 'Chasing the Culprits';
    91:  Result := 'The Grove';
    92:  Result := 'The Trial of Julius Zamon';
    95:  Result := 'Alpine Borderlands';
    96:  Result := 'Alpine Borderlands';
    97:  Result := 'Infiltration';
    110:  Result := 'The Perils of Friendship';
    111:  Result := 'Victory or Death';
    112:  Result := 'The Ruined City of Arah';
    113:  Result := 'Desperate Medicine';
    120:  Result := 'The Commander';
    138:  Result := 'Defense of Shaemoor';
    139:  Result := 'Rata Sum';
    140:  Result := 'The Apothecary';
    142:  Result := 'Going Undercover';
    143:  Result := 'Going Undercover';
    144:  Result := 'The Greater Good';
    145:  Result := 'The Rescue';
    147:  Result := 'Breaking the Blade';
    148:  Result := 'The Fall of Falcon Company';
    149:  Result := 'The Fall of Falcon Company';
    152:  Result := 'Confronting Captain Tervelan';
    153:  Result := 'Seek Logan''s Aid';
    154:  Result := 'Seek Logan''s Aid';
    157:  Result := 'Accusation';
    159:  Result := 'Accusation';
    161:  Result := 'Liberation';
    162:  Result := 'Voices From the Past';
    163:  Result := 'Voices From the Past';
    171:  Result := 'Rending the Mantle';
    172:  Result := 'Rending the Mantle';
    178:  Result := 'The Floating Grizwhirl';
    179:  Result := 'The Floating Grizwhirl';
    180:  Result := 'The Floating Grizwhirl';
    182:  Result := 'Clown College';
    184:  Result := 'The Artist''s Workshop';
    185:  Result := 'Into the Woods';
    186:  Result := 'The Ringmaster';
    190:  Result := 'The Orders of Tyria';
    191:  Result := 'The Orders of Tyria';
    192:  Result := 'Brute Force';
    193:  Result := 'Mortus Virge';
    195:  Result := 'Triskell Quay';
    196:  Result := 'Track the Seraph';
    198:  Result := 'Speaker of the Dead';
    199:  Result := 'The Sad Tale of the \"Ravenous\"';
    201:  Result := 'Kellach''s Attack';
    202:  Result := 'The Queen''s Justice';
    203:  Result := 'The Trap';
    211:  Result := 'Best Laid Plans';
    212:  Result := 'Welcome Home';
    215:  Result := 'The Tribune''s Call';
    216:  Result := 'The Tribune''s Call';
    217:  Result := 'The Tribune''s Call';
    218:  Result := 'Black Citadel';
    222:  Result := 'A Spy for a Spy';
    224:  Result := 'Scrapyard Dogs';
    225:  Result := 'A Spy for a Spy';
    226:  Result := 'On the Mend';
    232:  Result := 'Spilled Blood';
    234:  Result := 'Ghostbore Musket';
    237:  Result := 'Iron Grip of the Legion';
    238:  Result := 'The Flame Advances';
    239:  Result := 'The Flame Advances';
    242:  Result := 'Test Your Metal';
    244:  Result := 'Quick and Quiet';
    248:  Result := 'Salma District (Home)';
    249:  Result := 'An Unusual Inheritance';
    250:  Result := 'Windrock Maze';
    251:  Result := 'Mired Deep';
    252:  Result := 'Mired Deep';
    254:  Result := 'Deadly Force';
    255:  Result := 'Ghostbore Artillery';
    256:  Result := 'No Negotiations';
    257:  Result := 'Salvaging Scrap';
    258:  Result := 'Salvaging Scrap';
    259:  Result := 'In the Ruins';
    260:  Result := 'In the Ruins';
    261:  Result := 'Busted Flagon Public House';
    262:  Result := 'Chain of Command';
    263:  Result := 'Chain of Command';
    264:  Result := 'Time for a Promotion';
    267:  Result := 'The End of the Line';
    269:  Result := 'Magic Users';
    271:  Result := 'Rage Suppression';
    272:  Result := 'Rage Suppression';
    274:  Result := 'Operation: Bulwark';
    275:  Result := 'AWOL';
    276:  Result := 'Human''s Lament';
    282:  Result := 'Misplaced Faith';
    283:  Result := 'Thicker Than Water';
    284:  Result := 'Dishonorable Discharge';
    287:  Result := 'Searching for the Truth';
    288:  Result := 'Lighting the Beacons';
    290:  Result := 'Stoking the Flame';
    294:  Result := 'A Fork in the Road';
    295:  Result := 'Sins of the Father';
    297:  Result := 'Graveyard Ornaments';
    326:  Result := 'Hoelbrak';
    327:  Result := 'Desperate Medicine';
    330:  Result := 'Seraph Headquarters';
    334:  Result := 'Keg Brawl';
    335:  Result := 'Claw Island';
    336:  Result := 'Chantry of Secrets';
    350:  Result := 'Heart of the Mists';
    363:  Result := 'The Sting';
    364:  Result := 'Drawing Out the Cult';
    365:  Result := 'Ashes of the Past';
    371:  Result := 'Hero''s Canton (Home)';
    372:  Result := 'Blood Tribune Quarters';
    373:  Result := 'The Command Core';
    374:  Result := 'Knut Whitebear''s Loft';
    375:  Result := 'Hunter''s Hearth (Home)';
    376:  Result := 'Stonewright''s Steading';
    378:  Result := 'Queen''s Throne Room';
    379:  Result := 'The Great Hunt';
    380:  Result := 'A Weapon of Legend';
    381:  Result := 'The Last of the Giant-Kings';
    382:  Result := 'Disciples of the Dragon';
    385:  Result := 'A Weapon of Legend';
    386:  Result := 'Echoes of Ages Past';
    387:  Result := 'Wild Spirits';
    388:  Result := 'Out of the Skies';
    389:  Result := 'Echoes of Ages Past';
    390:  Result := 'Twilight of the Wolf';
    391:  Result := 'Rage of the Minotaurs';
    392:  Result := 'A Pup''s Illness';
    393:  Result := 'Through the Veil';
    394:  Result := 'A Trap Foiled';
    396:  Result := 'Raven''s Revered';
    397:  Result := 'One Good Drink Deserves Another';
    399:  Result := 'Shape of the Spirit';
    400:  Result := 'Into the Mists';
    401:  Result := 'Through the Veil';
    405:  Result := 'Blessed of Bear';
    407:  Result := 'The Wolf Havroun';
    410:  Result := 'Minotaur Rampant';
    411:  Result := 'Minotaur Rampant';
    412:  Result := 'Unexpected Visitors';
    413:  Result := 'Rumors of Trouble';
    414:  Result := 'A New Challenger';
    415:  Result := 'Unexpected Visitors';
    416:  Result := 'Roadblock';
    417:  Result := 'Assault on Moledavia';
    418:  Result := 'Don''t Leave Your Toys Out';
    419:  Result := 'A New Challenger';
    420:  Result := 'First Attack';
    421:  Result := 'The Finishing Blow';
    422:  Result := 'The Semifinals';
    423:  Result := 'The Championship Fight';
    424:  Result := 'The Championship Fight';
    425:  Result := 'The Machine in Action';
    427:  Result := 'Among the Kodan';
    428:  Result := 'Rumors of Trouble';
    429:  Result := 'Rage of the Minotaurs';
    430:  Result := 'Darkness at Drakentelt';
    432:  Result := 'Fighting the Nightmare';
    434:  Result := 'Preserving the Balance';
    435:  Result := 'Means to an End';
    436:  Result := 'Dredge Technology';
    439:  Result := 'Underground Scholar';
    440:  Result := 'Dredge Assault';
    441:  Result := 'The Dredge Hideout';
    444:  Result := 'Sabotage';
    447:  Result := 'Codebreaker';
    449:  Result := 'Armaments';
    453:  Result := 'Assault the Hill';
    454:  Result := 'Silent Warfare';
    455:  Result := 'Sever the Head';
    458:  Result := 'Fury of the Dead';
    459:  Result := 'A Fork in the Road';
    460:  Result := 'Citadel Stockade';
    464:  Result := 'Tribunes in Effigy';
    465:  Result := 'Sins of the Father';
    466:  Result := 'Misplaced Faith';
    469:  Result := 'Gladiator';
    470:  Result := 'Graveyard Ornaments';
    471:  Result := 'Undead Infestation';
    474:  Result := 'Whispers in the Dark';
    476:  Result := 'Dangerous Research';
    477:  Result := 'Digging Up Answers';
    480:  Result := 'Defending the Keep';
    481:  Result := 'Undead Detection';
    483:  Result := 'Ever Vigilant';
    485:  Result := 'Research and Destroy';
    487:  Result := 'Whispers of Vengeance';
    488:  Result := 'Killer Instinct';
    489:  Result := 'Meeting my Mentor';
    490:  Result := 'A Fragile Peace';
    492:  Result := 'Don''t Shoot the Messenger';
    496:  Result := 'Meeting my Mentor';
    497:  Result := 'Dredging Up the Past';
    498:  Result := 'Dredging Up the Past';
    499:  Result := 'Scrapyard Dogs';
    502:  Result := 'Quaestor''s Siege';
    503:  Result := 'Minister''s Defense';
    504:  Result := 'Called to Service';
    505:  Result := 'Called to Service';
    507:  Result := 'Mockery of Death';
    509:  Result := 'Discovering Darkness';
    511:  Result := 'Hounds and the Hunted';
    512:  Result := 'Hounds and the Hunted';
    513:  Result := 'Loved and Lost';
    514:  Result := 'Saving the Stag';
    515:  Result := 'Hidden in Darkness';
    516:  Result := 'Good Work Spoiled';
    517:  Result := 'Black Night, White Stag';
    518:  Result := 'The Omphalos Chamber';
    519:  Result := 'Weakness of the Heart';
    520:  Result := 'Awakening';
    521:  Result := 'Holding Back the Darkness';
    522:  Result := 'A Sly Trick';
    523:  Result := 'Deep Tangled Roots';
    524:  Result := 'The Heart of Nightmare';
    525:  Result := 'Beneath a Cold Moon';
    527:  Result := 'The Knight''s Duel';
    528:  Result := 'Hammer and Steel';
    529:  Result := 'Where Life Goes';
    532:  Result := 'After the Storm';
    533:  Result := 'After the Storm';
    534:  Result := 'Beneath the Waves';
    535:  Result := 'Mirror, Mirror';
    536:  Result := 'A Vision of Darkness';
    537:  Result := 'Shattered Light';
    538:  Result := 'An Unknown Soul';
    539:  Result := 'An Unknown Soul';
    540:  Result := 'Where Life Goes';
    542:  Result := 'Source of the Issue';
    543:  Result := 'Wild Growth';
    544:  Result := 'Wild Growth';
    545:  Result := 'Seeking the Zalisco';
    546:  Result := 'The Direct Approach';
    547:  Result := 'Trading Trickery';
    548:  Result := 'Eye of the Sun';
    549:  Result := 'Battle of Kyhlo';
    552:  Result := 'Seeking the Zalisco';
    554:  Result := 'Forest of Niflhel';
    556:  Result := 'A Different Dream';
    557:  Result := 'A Splinter in the Flesh';
    558:  Result := 'Shadow of the Tree';
    559:  Result := 'Eye of the Sun';
    560:  Result := 'Sharpened Thorns';
    561:  Result := 'Bramble Walls';
    563:  Result := 'Secrets in the Earth';
    564:  Result := 'The Blossom of Youth';
    566:  Result := 'The Bad Apple';
    567:  Result := 'Trouble at the Roots';
    569:  Result := 'Flower of Death';
    570:  Result := 'Dead of Winter';
    571:  Result := 'A Tangle of Weeds';
    573:  Result := 'Explosive Intellect';
    574:  Result := 'In Snaff''s Footsteps';
    575:  Result := 'Golem Positioning System';
    576:  Result := 'Monkey Wrench';
    577:  Result := 'Defusing the Problem';
    578:  Result := 'The Things We Do For Love';
    579:  Result := 'The Snaff Prize';
    581:  Result := 'A Sparkling Rescue';
    582:  Result := 'High Maintenance';
    583:  Result := 'Snaff Would Be Proud';
    584:  Result := 'Taking Credit Back';
    586:  Result := 'Political Homicide';
    587:  Result := 'Here, There, Everywhere';
    588:  Result := 'Piece Negotiations';
    589:  Result := 'Readings On the Rise';
    590:  Result := 'Snaff Would Be Proud';
    591:  Result := 'Readings On the Rise';
    592:  Result := 'Unscheduled Delay';
    594:  Result := 'Stand By Your Krewe';
    595:  Result := 'Unwelcome Visitors';
    596:  Result := 'Where Credit Is Due';
    597:  Result := 'Where Credit Is Due';
    598:  Result := 'Short Fuse';
    599:  Result := 'Short Fuse';
    606:  Result := 'Salt in the Wound';
    607:  Result := 'Free Rein';
    608:  Result := 'Serving Up Trouble';
    609:  Result := 'Serving Up Trouble';
    610:  Result := 'Flash Flood';
    611:  Result := 'I Smell a Rat';
    613:  Result := 'Magnum Opus';
    614:  Result := 'Magnum Opus';
    617:  Result := 'Bad Business';
    618:  Result := 'Beta Test';
    619:  Result := 'Beta Test';
    620:  Result := 'Any Sufficiently Advanced Science';
    621:  Result := 'Any Sufficiently Advanced Science';
    622:  Result := 'Bad Forecast';
    623:  Result := 'Industrial Espionage';
    624:  Result := 'Split Second';
    625:  Result := 'Carry a Big Stick';
    627:  Result := 'Meeting my Mentor';
    628:  Result := 'Stealing Secrets';
    629:  Result := 'A Bold New Theory';
    630:  Result := 'Forging Permission';
    631:  Result := 'Forging Permission';
    633:  Result := 'Setting the Stage';
    634:  Result := 'Containment';
    635:  Result := 'Containment';
    636:  Result := 'Hazardous Environment';
    638:  Result := 'Down the Hatch';
    639:  Result := 'Down the Hatch';
    642:  Result := 'The Stone Sheath';
    643:  Result := 'Bad Blood';
    644:  Result := 'Test Subject';
    645:  Result := 'Field Test';
    646:  Result := 'The House of Caithe';
    647:  Result := 'Dreamer''s Terrace (Home)';
    648:  Result := 'The Omphalos Chamber';
    649:  Result := 'Snaff Memorial Lab';
    650:  Result := 'Applied Development Lab (Home)';
    651:  Result := 'Council Level';
    652:  Result := 'A Meeting of the Minds';
    653:  Result := 'Mightier than the Sword';
    654:  Result := 'They Went Thataway';
    655:  Result := 'Lines of Communication';
    656:  Result := 'Untamed Wilds';
    657:  Result := 'An Apple a Day';
    658:  Result := 'Base of Operations';
    659:  Result := 'The Lost Chieftain''s Return';
    660:  Result := 'Thrown Off Guard';
    662:  Result := 'Pets and Walls Make Stronger Kraals';
    663:  Result := 'Doubt';
    664:  Result := 'The False God''s Lair';
    666:  Result := 'Bad Ice';
    667:  Result := 'Bad Ice';
    668:  Result := 'Pets and Walls Make Stronger Kraals';
    669:  Result := 'Attempted Deicide';
    670:  Result := 'Doubt';
    672:  Result := 'Rat-Tastrophe';
    673:  Result := 'Salvation Through Heresy';
    674:  Result := 'Enraged and Unashamed';
    675:  Result := 'Pastkeeper';
    676:  Result := 'Protest Too Much';
    677:  Result := 'Prying the Eye Open';
    678:  Result := 'The Hatchery';
    680:  Result := 'Convincing the Faithful';
    681:  Result := 'Evacuation';
    682:  Result := 'Untamed Wilds';
    683:  Result := 'Champion''s Sacrifice';
    684:  Result := 'Thieving from Thieves';
    685:  Result := 'Crusader''s Return';
    686:  Result := 'Unholy Grounds';
    687:  Result := 'Chosen of the Sun';
    691:  Result := 'Set to Blow';
    692:  Result := 'Gadd''s Last Gizmo';
    693:  Result := 'Library Science';
    694:  Result := 'Rakt and Ruin';
    695:  Result := 'Suspicious Activity';
    696:  Result := 'Reconnaissance';
    697:  Result := 'Critical Blowback';
    698:  Result := 'The Battle of Claw Island';
    699:  Result := 'Suspicious Activity';
    700:  Result := 'Priory Library';
    701:  Result := 'On Red Alert';
    702:  Result := 'Forearmed Is Forewarned';
    703:  Result := 'The Oratory';
    704:  Result := 'Killing Fields';
    705:  Result := 'The Ghost Rite';
    706:  Result := 'The Good Fight';
    707:  Result := 'Defense Contract';
    708:  Result := 'Shards of Orr';
    709:  Result := 'The Sound of Psi-Lance';
    710:  Result := 'Early Parole';
    711:  Result := 'Magic Sucks';
    712:  Result := 'A Light in the Darkness';
    713:  Result := 'The Priory Assailed';
    714:  Result := 'Under Siege';
    715:  Result := 'Retribution';
    716:  Result := 'Retribution';
    719:  Result := 'The Sound of Psi-Lance';
    726:  Result := 'Wet Work';
    727:  Result := 'Shell Shock';
    728:  Result := 'Volcanic Extraction';
    729:  Result := 'Munition Acquisition';
    730:  Result := 'To the Core';
    731:  Result := 'The Battle of Fort Trinity';
    732:  Result := 'Tower Down';
    733:  Result := 'Forging the Pact';
    735:  Result := 'Willing Captives';
    736:  Result := 'Marshaling the Truth';
    737:  Result := 'Breaking the Bone Ship';
    738:  Result := 'Liberating Apatia';
    739:  Result := 'Liberating Apatia';
    743:  Result := 'Fixing the Blame';
    744:  Result := 'A Sad Duty';
    745:  Result := 'Striking off the Chains';
    746:  Result := 'Delivering Justice';
    747:  Result := 'Intercepting the Orb';
    750:  Result := 'Close the Eye';
    751:  Result := 'Through the Looking Glass';
    758:  Result := 'The Cathedral of Silence';
    760:  Result := 'Starving the Beast';
    761:  Result := 'Stealing Light';
    762:  Result := 'Hunters and Prey';
    763:  Result := 'Romke''s Final Voyage';
    764:  Result := 'Marching Orders';
    766:  Result := 'Air Drop';
    767:  Result := 'Estate of Decay';
    768:  Result := 'What the Eye Beholds';
    769:  Result := 'Conscript the Dead Ships';
    772:  Result := 'Ossuary of Unquiet Dead';
    775:  Result := 'Temple of the Forgotten God';
    776:  Result := 'Temple of the Forgotten God';
    777:  Result := 'Temple of the Forgotten God';
    778:  Result := 'Through the Looking Glass';
    779:  Result := 'Starving the Beast';
    780:  Result := 'Against the Corruption';
    781:  Result := 'The Source of Orr';
    782:  Result := 'Armor Guard';
    783:  Result := 'Blast from the Past';
    784:  Result := 'The Steel Tide';
    785:  Result := 'Further Into Orr';
    786:  Result := 'Ships of the Line';
    787:  Result := 'Source of Orr';
    788:  Result := 'Victory or Death';
    789:  Result := 'A Grisly Shipment';
    790:  Result := 'Blast from the Past';
    792:  Result := 'A Pup''s Illness';
    793:  Result := 'Hunters and Prey';
    795:  Result := 'Legacy of the Foefire';
    796:  Result := 'The Informant';
    797:  Result := 'A Traitor''s Testimony';
    799:  Result := 'Follow the Trail';
    806:  Result := 'Awakening';
    807:  Result := 'Eye of the North';
    820:  Result := 'The Omphalos Chamber';
    821:  Result := 'The Omphalos Chamber';
    825:  Result := 'Codebreaker';
    827:  Result := 'Caer Aval';
    828:  Result := 'The Durmand Priory';
    830:  Result := 'Vigil Headquarters';
    833:  Result := 'Ash Tribune Quarters';
    845:  Result := 'Shattered Light';
    862:  Result := 'Reaper''s Rumble';
    863:  Result := 'Ascent to Madness';
    864:  Result := 'Lunatic Inquisition';
    865:  Result := 'Mad King''s Clock Tower';
    866:  Result := 'Mad King''s Labyrinth';
    872:  Result := 'Fractals of the Mists';
    873:  Result := 'Southsun Cove';
    875:  Result := 'Temple of the Silent Storm';
    877:  Result := 'Snowball Mayhem';
    878:  Result := 'Tixx''s Infinirarium';
    880:  Result := 'Toypocalypse';
    881:  Result := 'Bell Choir Ensemble';
    882:  Result := 'Winter Wonderland';
    894:  Result := 'Spirit Watch';
    895:  Result := 'Super Adventure Box';
    896:  Result := 'North Nolan Hatchery';
    897:  Result := 'Cragstead';
    899:  Result := 'Obsidian Sanctum';
    900:  Result := 'Skyhammer';
    901:  Result := 'Molten Furnace';
    905:  Result := 'Crab Toss';
    911:  Result := 'Dragon Ball Arena';
    912:  Result := 'Ceremony and Acrimony? Memorials on the Pyre';
    913:  Result := 'Hard Boiled The Scene of the Crime';
    914:  Result := 'The Dead End';
    915:  Result := 'Aetherblade Retreat';
    917:  Result := 'No More Secrets? The Scene of the Crime';
    918:  Result := 'Aspect Arena';
    919:  Result := 'Sanctum Sprint';
    920:  Result := 'Southsun Survival';
    922:  Result := 'Labyrinthine Cliffs';
    924:  Result := 'Grandmaster of Om';
    929:  Result := 'The Crown Pavilion';
    930:  Result := 'Opening Ceremony';
    931:  Result := 'Scarlet''s Playhouse';
    932:  Result := 'Closing Ceremony';
    934:  Result := 'Super Adventure Box';
    935:  Result := 'Super Adventure Box';
    937:  Result := 'Scarlet''s End';
    943:  Result := 'The Tower of Nightmares (Public)';
    945:  Result := 'The Nightmare Ends';
    947:  Result := 'Fractals of the Mists';
    948:  Result := 'Fractals of the Mists';
    949:  Result := 'Fractals of the Mists';
    950:  Result := 'Fractals of the Mists';
    951:  Result := 'Fractals of the Mists';
    952:  Result := 'Fractals of the Mists';
    953:  Result := 'Fractals of the Mists';
    954:  Result := 'Fractals of the Mists';
    955:  Result := 'Fractals of the Mists';
    956:  Result := 'Fractals of the Mists';
    957:  Result := 'Fractals of the Mists';
    958:  Result := 'Fractals of the Mists';
    959:  Result := 'Fractals of the Mists';
    960:  Result := 'Fractals of the Mists';
    964:  Result := 'Scarlet''s Secret Lair';
    965:  Result := 'The Origins of Madness: A Moment''s Peace';
    968:  Result := 'Edge of the Mists';
    971:  Result := 'The Dead End: A Study in Scarlet';
    973:  Result := 'The Evacuation of Lion''s Arch';
    980:  Result := 'The Dead End: Celebration';
    984:  Result := 'Courtyard';
    987:  Result := 'Lion''s Arch: Honored Guests';
    988:  Result := 'Dry Top';
    989:  Result := 'Prosperity''s Mystery';
    990:  Result := 'Cornered';
    991:  Result := 'Disturbance in Brisban Wildlands';
    992:  Result := 'Fallen Hopes';
    993:  Result := 'Scarlet''s Secret Room';
    994:  Result := 'The Concordia Incident';
    997:  Result := 'Discovering Scarlet''s Breakthrough';
    998:  Result := 'The Machine';
    999:  Result := 'Trouble at Fort Salma';
    1000:  Result := 'The Waypoint Conundrum';
    1001:  Result := 'Summit Invitations';
    1002:  Result := 'Mission Accomplished';
    1003:  Result := 'Rallying Call';
    1004:  Result := 'Plan of Attack';
    1005:  Result := 'Party Politics';
    1006:  Result := 'Foefire Cleansing';
    1007:  Result := 'Recalibrating the Waypoints';
    1008:  Result := 'The Ghosts of Fort Salma';
    1009:  Result := 'Taimi''s Device';
    1010:  Result := 'The World Summit';
    1011:  Result := 'Battle of Champion''s Dusk';
    1015:  Result := 'The Silverwastes';
    1016:  Result := 'Hidden Arcana';
    1017:  Result := 'Reunion with the Pact';
    1018:  Result := 'Caithe''s Reconnaissance Squad';
    1019:  Result := 'Fort Trinity';
    1021:  Result := 'Into the Labyrinth';
    1022:  Result := 'Return to Camp Resolve';
    1023:  Result := 'Tracking the Aspect Masters';
    1024:  Result := 'No Refuge';
    1025:  Result := 'The Newly Awakened';
    1026:  Result := 'Meeting the Asura';
    1027:  Result := 'Pact Assaulted';
    1028:  Result := 'The Mystery Cave';
    1029:  Result := 'Arcana Obscura';
    1032:  Result := 'Prized Possessions';
    1033:  Result := 'Buried Insight';
    1037:  Result := 'The Jungle Provides';
    1040:  Result := 'Hearts and Minds';
    1041:  Result := 'Dragon''s Stand';
    1042:  Result := 'Verdant Brink';
    1043:  Result := 'Auric Basin';
    1045:  Result := 'Tangled Depths';
    1046:  Result := 'Roots of Terror';
    1048:  Result := 'City of Hope';
    1050:  Result := 'Torn from the Sky';
    1051:  Result := 'Prisoners of the Dragon';
    1052:  Result := 'Verdant Brink';
    1054:  Result := 'Bitter Harvest';
    1057:  Result := 'Strange Observations';
    1058:  Result := 'Prologue: Rally to Maguuma';
    1062:  Result := 'Spirit Vale';
    1063:  Result := 'Southsun Crab Toss';
    1064:  Result := 'Claiming the Lost Precipice';
    1065:  Result := 'Angvar''s Trove';
    1066:  Result := 'Claiming the Gilded Hollow';
    1067:  Result := 'Angvar''s Trove';
    1068:  Result := 'Gilded Hollow';
    1069:  Result := 'Lost Precipice';
    1070:  Result := 'Claiming the Lost Precipice';
    1071:  Result := 'Lost Precipice';
    1072:  Result := 'Southsun Crab Toss';
    1073:  Result := 'Guild Initiative Office';
    1074:  Result := 'Blightwater Shatterstrike';
    1075:  Result := 'Proxemics Lab';
    1076:  Result := 'Lost Precipice';
    1078:  Result := 'Claiming the Gilded Hollow';
    1079:  Result := 'Deep Trouble';
    1080:  Result := 'Branded for Termination';
    1081:  Result := 'Langmar Estate';
    1082:  Result := 'Langmar Estate';
    1083:  Result := 'Deep Trouble';
    1084:  Result := 'Southsun Crab Toss';
    1086:  Result := 'Save Our Supplies';
    1087:  Result := 'Proxemics Lab';
    1088:  Result := 'Claiming the Gilded Hollow';
    1089:  Result := 'Angvar''s Trove';
    1090:  Result := 'Langmar Estate';
    1091:  Result := 'Save Our Supplies';
    1092:  Result := 'Scratch Sentry Defense';
    1093:  Result := 'Angvar''s Trove';
    1094:  Result := 'Save Our Supplies';
    1095:  Result := 'Dragon''s Stand (Heart of Thorns)';
    1097:  Result := 'Proxemics Lab';
    1098:  Result := 'Claiming the Gilded Hollow';
    1099:  Result := 'Desert Borderlands';
    1100:  Result := 'Scratch Sentry Defense';
    1101:  Result := 'Gilded Hollow';
    1104:  Result := 'Lost Precipice';
    1105:  Result := 'Langmar Estate';
    1106:  Result := 'Deep Trouble';
    1107:  Result := 'Gilded Hollow';
    1108:  Result := 'Gilded Hollow';
    1109:  Result := 'Angvar''s Trove';
    1110:  Result := 'Scrap Rifle Field Test';
    1111:  Result := 'Scratch Sentry Defense';
    1112:  Result := 'Branded for Termination';
    1113:  Result := 'Scratch Sentry Defense';
    1115:  Result := 'Haywire Punch-o-Matic Battle';
    1116:  Result := 'Deep Trouble';
    1117:  Result := 'Claiming the Lost Precipice';
    1118:  Result := 'Save Our Supplies';
    1121:  Result := 'Gilded Hollow';
    1122:  Result := 'Claiming the Gilded Hollow';
    1123:  Result := 'Blightwater Shatterstrike';
    1124:  Result := 'Lost Precipice';
    1126:  Result := 'Southsun Crab Toss';
    1128:  Result := 'Scratch Sentry Defense';
    1129:  Result := 'Langmar Estate';
    1130:  Result := 'Deep Trouble';
    1131:  Result := 'Blightwater Shatterstrike';
    1132:  Result := 'Claiming the Lost Precipice';
    1133:  Result := 'Branded for Termination';
    1134:  Result := 'Blightwater Shatterstrike';
    1135:  Result := 'Branded for Termination';
    1136:  Result := 'Proxemics Lab';
    1137:  Result := 'Proxemics Lab';
    1138:  Result := 'Save Our Supplies';
    1139:  Result := 'Southsun Crab Toss';
    1140:  Result := 'Claiming the Lost Precipice';
    1142:  Result := 'Blightwater Shatterstrike';
    1146:  Result := 'Branded for Termination';
    1147:  Result := 'Spirit Vale';
    1149:  Result := 'Salvation Pass';
    1150:  Result := '';
    1153:  Result := 'Tiger Den';
    1154:  Result := 'Special Forces Training Area';
    1155:  Result := 'Lion''s Arch Aerodrome';
    1156:  Result := 'Stronghold of the Faithful';
    1158:  Result := 'Noble''s Folly';
    1159:  Result := 'Research in Rata Novus';
    1161:  Result := 'Eir''s Homestead';
    1163:  Result := 'Revenge of the Capricorn';
    1164:  Result := 'Fractals of the Mists';
    1165:  Result := 'Bloodstone Fen';
    1166:  Result := 'Confessor''s Stronghold';
    1167:  Result := 'A Shadow''s Deeds';
    1169:  Result := 'Rata Novus';
    1170:  Result := 'Taimi''s Game';
    1171:  Result := 'Eternal Coliseum';
    1172:  Result := 'Dragon Vigil';
    1173:  Result := 'Taimi''s Game';
    1175:  Result := 'Ember Bay';
    1176:  Result := 'Taimi''s Game';
    1177:  Result := 'Fractals of the Mists';
    1178:  Result := 'Bitterfrost Frontier';
    1180:  Result := 'The Bitter Cold';
    1181:  Result := 'Frozen Out';
    1182:  Result := 'Precocious Aurene';
    1185:  Result := 'Lake Doric';
    1188:  Result := 'Bastion of the Penitent';
    1189:  Result := 'Regrouping with the Queen';
    1190:  Result := 'A Meeting of Ministers';
    1191:  Result := 'Confessor''s End';
    1192:  Result := 'The Second Vision';
    1193:  Result := 'The First Vision';
    1194:  Result := 'The Sword Regrown';
    1195:  Result := 'Draconis Mons';
    1196:  Result := 'Heart of the Volcano';
    1198:  Result := 'Taimi''s Pet Project';
    1200:  Result := 'Hall of the Mists';
    1201:  Result := 'Asura Arena';
    1202:  Result := 'White Mantle Hideout';
    1203:  Result := 'Siren''s Landing';
    1204:  Result := 'Palace Temple';
    1205:  Result := 'Fractals of the Mists';
    1206:  Result := 'Mistlock Sanctuary';
    1207:  Result := 'The Last Chance';
    1208:  Result := 'Shining Blade Headquarters';
    1209:  Result := 'The Sacrifice';
    1210:  Result := 'Crystal Oasis';
    1211:  Result := 'Desert Highlands';
    1212:  Result := 'Office of the Chief Councilor';
    1214:  Result := 'Windswept Haven';
    1215:  Result := 'Windswept Haven';
    1217:  Result := 'Sparking the Flame';
    1219:  Result := 'Enemy of My Enemy: The Beastmarshal';
    1220:  Result := 'Sparking the Flame (Prologue)';
    1221:  Result := 'The Way Forward';
    1222:  Result := 'Claiming Windswept Haven';
    1223:  Result := 'Small Victory (Epilogue)';
    1224:  Result := 'Windswept Haven';
    1226:  Result := 'The Desolation';
    1227:  Result := 'Hallowed Ground: Tomb of Primeval Kings';
    1228:  Result := 'Elon Riverlands';
    1230:  Result := 'Facing the Truth: The Sanctum';
    1231:  Result := 'Claiming Windswept Haven';
    1232:  Result := 'Windswept Haven';
    1234:  Result := 'To Kill a God';
    1236:  Result := 'Claiming Windswept Haven';
    1240:  Result := 'Blazing a Trail';
    1241:  Result := 'Night of Fires';
    1242:  Result := 'Zalambur''s Office';
    1243:  Result := 'Windswept Haven';
    1244:  Result := 'Claiming Windswept Haven';
    1245:  Result := 'The Departing';
    1246:  Result := 'Captain Kiel''s Office';
    1247:  Result := 'Enemy of My Enemy';
    1248:  Result := 'Domain of Vabbi';
    1250:  Result := 'Windswept Haven';
    1252:  Result := 'Crystalline Memories';
    1253:  Result := 'Beast of War';
    1255:  Result := 'Enemy of My Enemy: The Troopmarshal';
    1256:  Result := 'The Dark Library';
    1257:  Result := 'Spearmarshal''s Lament';
    1260:  Result := 'Eye of the Brandstorm';
    1263:  Result := 'Domain of Istan';
    1264:  Result := 'Hall of Chains';
    1265:  Result := 'The Hero of Istan';
    1266:  Result := 'Cave of the Sunspear Champion';
    1267:  Result := 'Fractals of the Mists';
    1268:  Result := 'Fahranur, the First City';
    1270:  Result := 'Toypocalypse';
    1271:  Result := 'Sandswept Isles';
    1274:  Result := 'The Charge';
    1275:  Result := 'Courtyard';
    1276:  Result := 'The Test Subject';
    1277:  Result := 'The Charge';
    1278:  Result := '???';
    1279:  Result := 'ERROR: SIGNAL LOST';
    1281:  Result := 'A Kindness Repaid';
    1282:  Result := 'Tracking the Scientist';
    1283:  Result := '???';
    1285:  Result := '???';
    1288:  Result := 'Domain of Kourna';
    1289:  Result := 'Seized';
    1290:  Result := 'Fractals of the Mists';
    1291:  Result := 'Forearmed Is Forewarned';
    1292:  Result := 'Be My Guest';
    1294:  Result := 'Sun''s Refuge';
    1295:  Result := 'Legacy';
    1296:  Result := 'Storm Tracking';
    1297:  Result := 'A Shattered Nation';
    1299:  Result := 'Storm Tracking';
    1300:  Result := 'From the Ashes? The Deadeye';
    1301:  Result := 'Jahai Bluffs';
    1302:  Result := 'Storm Tracking';
    1303:  Result := 'Mythwright Gambit';
    1304:  Result := 'Mad King''s Raceway';
    1305:  Result := 'Djinn''s Dominion';
    1306:  Result := 'Secret Lair of the Snowmen (Squad)';
    1308:  Result := 'Scion \u0026 Champion';
    1309:  Result := 'Fractals of the Mists';
    1310:  Result := 'Thunderhead Peaks';
    1313:  Result := 'The Crystal Dragon';
    1314:  Result := 'The Crystal Blooms';
    1315:  Result := 'Armistice Bastion';
    1316:  Result := 'Mists Rift';
    1317:  Result := 'Dragonfall';
    1318:  Result := 'Dragonfall';
    1319:  Result := 'Descent';
    1320:  Result := 'The End';
    1321:  Result := 'Dragonflight';
    1322:  Result := 'Epilogue';
    1323:  Result := 'The Key of Ahdashim';
    1326:  Result := 'Dragon Arena (Public)';
    1327:  Result := 'Dragon Arena (Private)';
    1328:  Result := 'Auric Span';
    1329:  Result := 'Coming Home';
    1330:  Result := 'Grothmar Valley';
    1331:  Result := 'Strike Mission: Shiverpeaks Pass (Public)';
    1332:  Result := 'Strike Mission: Shiverpeaks Pass (Squad)';
    1334:  Result := 'Deeper and Deeper';
    1336:  Result := 'A Race to Arms';
    1338:  Result := 'Bad Blood';
    1339:  Result := 'Weekly Strike Mission: Boneskinner (Squad)';
    1340:  Result := 'Weekly Strike Mission: Voice of the Fallen and Claw of the Fallen (Public)';
    1341:  Result := 'Weekly Strike Mission: Fraenir of Jormag (Squad)';
    1342:  Result := 'The Invitation';
    1343:  Result := 'Bjora Marches';
    1344:  Result := 'Weekly Strike Mission: Fraenir of Jormag (Public)';
    1345:  Result := 'What''s Left Behind';
    1346:  Result := 'Weekly Strike Mission: Voice of the Fallen and Claw of the Fallen (Squad)';
    1349:  Result := 'Silence';
    1351:  Result := 'Weekly Strike Mission: Boneskinner (Public)';
    1352:  Result := 'Secret Lair of the Snowmen (Public)';
    1353:  Result := 'Celestial Challenge';
    1355:  Result := 'Voice in the Deep';
    1356:  Result := 'Chasing Ghosts';
    1357:  Result := 'Strike Mission: Whisper of Jormag (Public)';
    1358:  Result := 'Eye of the North';
    1359:  Result := 'Strike Mission: Whisper of Jormag (Squad)';
    1361:  Result := 'The Nightmare Incarnate';
    1362:  Result := 'Forging Steel (Public)';
    1363:  Result := 'New Friends, New Enemies�North Nolan Hatchery';
    1364:  Result := 'The Battle for Cragstead';
    1366:  Result := 'Darkrime Delves';
    1368:  Result := 'Forging Steel (Squad)';
    1369:  Result := 'Canach''s Lair';
    1370:  Result := 'Eye of the North';
    1371:  Result := 'Drizzlewood Coast';
    1372:  Result := 'Turnabout';
    1373:  Result := 'Pointed Parley';
    1374:  Result := 'Strike Mission: Cold War (Squad)';
    1375:  Result := 'Snapping Steel';
    1376:  Result := 'Strike Mission: Cold War (Public)';
    1378:  Result := 'Behind Enemy Lines';
    1379:  Result := 'One Charr, One Dragon, One Champion';
    1380:  Result := 'Epilogue';
    1382:  Result := 'Arena of the Wolverine';
    1383:  Result := 'A Simple Negotiation';
    1384:  Result := 'Fractals of the Mists';
    1385:  Result := 'Caledon Forest (Private)';
    1386:  Result := 'Thunderhead Peaks (Private)';
    1387:  Result := 'Bloodtide Coast (Public)';
    1388:  Result := 'Snowden Drifts (Private)';
    1389:  Result := 'Snowden Drifts (Public)';
    1390:  Result := 'Fireheart Rise (Public)';
    1391:  Result := 'Brisban Wildlands (Private)';
    1392:  Result := 'Primordus Rising';
    1393:  Result := 'Lake Doric (Public)';
    1394:  Result := 'Bloodtide Coast (Private)';
    1395:  Result := 'Thunderhead Peaks (Public)';
    1396:  Result := 'Gendarran Fields (Public)';
    1397:  Result := 'Metrica Province (Public)';
    1398:  Result := 'Fields of Ruin (Public)';
    1399:  Result := 'Brisban Wildlands (Public)';
    1400:  Result := 'Fields of Ruin (Private)';
    1401:  Result := 'Metrica Province (Private)';
    1402:  Result := 'Lake Doric (Private)';
    1403:  Result := 'Caledon Forest (Public)';
    1404:  Result := 'Fireheart Rise (Private)';
    1405:  Result := 'Gendarran Fields (Private)';
    1407:  Result := 'Council Level';
    1408:  Result := 'Wildfire';
    1409:  Result := 'Dragonstorm (Private Squad)';
    1410:  Result := 'Champion''s End';
    1411:  Result := 'Dragonstorm (Public)';
    1412:  Result := 'Dragonstorm';
    1413:  Result := 'The Twisted Marionette (Public)';
    1414:  Result := 'The Twisted Marionette (Private Squad)';
    1415:  Result := 'The Future in Jade: Power Plant';
    1416:  Result := 'Deepest Secrets: Yong Reactor';
    1419:  Result := 'Isle of Reflection';
    1420:  Result := 'Fallout: Nika''s Blade';
    1421:  Result := '???';
    1422:  Result := 'Dragon''s End';
    1426:  Result := 'Isle of Reflection';
    1427:  Result := 'Weight of the World: Lady Joon''s Estate';
    1428:  Result := 'Arborstone';
    1429:  Result := 'The Cycle, Reborn: Arborstone';
    1430:  Result := 'Claiming the Isle of Reflection';
    1432:  Result := 'Strike Mission: Aetherblade Hideout';
    1433:  Result := 'Old Friends';
    1434:  Result := 'Empty';
    1435:  Result := 'Isle of Reflection';
    1436:  Result := 'Extraction Point: Command Quarters';
    1437:  Result := 'Strike Mission: Harvest Temple';
    1438:  Result := 'New Kaineng City';
    1439:  Result := 'The Only One';
    1440:  Result := 'Laying to Rest';
    1442:  Result := 'Seitung Province';
    1444:  Result := 'Isle of Reflection';
    1445:  Result := 'The Future in Jade: Nahpui Lab';
    1446:  Result := 'Aetherblade Armada';
    1448:  Result := 'The Cycle, Reborn: The Dead End Bar';
    1449:  Result := 'Aurene''s Sanctuary';
    1450:  Result := 'Strike Mission: Xunlai Jade Junkyard';
    1451:  Result := 'Strike Mission: Kaineng Overlook';
    1452:  Result := 'The Echovald Wilds';
    1453:  Result := 'Ministry of Security: Main Office';
    1454:  Result := 'The Scenic Route: Kaineng Docks';
    1456:  Result := 'Claiming the Isle of Reflection';
    1457:  Result := 'Detention Facility';
    1458:  Result := 'Aurene''s Sanctuary';
    1459:  Result := 'Claiming the Isle of Reflection';
    1460:  Result := 'Empress Ihn''s Court';
    1461:  Result := 'Zen Daijun Hideaway';
    1462:  Result := 'Isle of Reflection';
    1463:  Result := 'Claiming the Isle of Reflection';
    1464:  Result := 'Fallout: Arborstone';
    1465:  Result := 'Thousand Seas Pavilion';
    1466:  Result := 'A Quiet Celebration�Knut Whitebear''s Loft';
    1467:  Result := 'New Friends, New Enemies�The Command Core';
    1468:  Result := 'The Battle for Cragstead�Knut Whitebear''s Loft';
    1469:  Result := 'New Friends, New Enemies�Blood Tribune Quarters';
    1470:  Result := 'A Quiet Celebration�Citadel Stockade';
    1471:  Result := 'Case Closed? The Dead End';
    1472:  Result := 'Hard Boiled? The Dead End';
    1474:  Result := 'Picking Up the Pieces';
    1477:  Result := 'The Tower of Nightmares (Private Squad)';
    1478:  Result := 'The Battle for Lion''s Arch (Private Squad)';
    1480:  Result := 'The Twisted Marionette';
    1481:  Result := 'Battle on the Breachmaker';
    1482:  Result := 'The Battle For Lion''s Arch (Public)';
    1483:  Result := 'Memory of Old Lion''s Arch';
    1484:  Result := 'North Evacuation Camp';
    1485:  Result := 'Strike Mission: Old Lion''s Court';
    1487:  Result := 'The Aether Escape';
    1488:  Result := 'On the Case: Excavation Yard';
    1489:  Result := 'A Raw Deal: Red Duck Teahouse';
    1490:  Result := 'Gyala Delve';
    1491:  Result := 'Deep Trouble: Excavation Yard';
    1492:  Result := 'Deep Trouble: The Deep';
    1494:  Result := 'Entrapment: The Deep';
    1495:  Result := 'A Plan Emerges: Power Plant';
    1496:  Result := 'Emotional Release: Jade Pools';
    1497:  Result := 'Emotional Release: Command Quarters';
    1498:  Result := 'Full Circle: Red Duck Teahouse';
    1499:  Result := 'Forward';
    1500:  Result := 'Fractals of the Mists';
    1501:  Result := 'Hell Breaks Loose: ???';
    1502:  Result := 'The Missing Facet: Southern Wizard''s Tower';
    1503:  Result := 'Mother of Stars: Stargaze Ridge';
    1504:  Result := 'Into the Obscure: Bastion of the Obscure';
    1506:  Result := 'Tower of Secrets: Southern Wizard''s Tower';
    1507:  Result := 'Mabon''s Fate: Bastion of Strength';
    1508:  Result := 'Astral Ward Infirmary';
    1509:  Result := 'The Wizard''s Tower';
    1510:  Result := 'Skywatch Archipelago';
    1511:  Result := 'Commander without a Cause: Gendarran Fields';
    1512:  Result := 'The World Spire: Bastion of the Celestial';
    1513:  Result := 'Mother of Stars: Cosmic Observatory';
    1514:  Result := 'Epilogue: The Wizard''s Tower';
    1515:  Result := 'Strike Mission: Cosmic Observatory';
    1516:  Result := 'Into the Obscure: The Wizard''s Tower';
    1517:  Result := 'Amnytas';
    1518:  Result := 'Treachery: Nayos';
    1519:  Result := 'Hell Breaks Loose: ???';
    1520:  Result := 'Strike Mission: Temple of Febe';
    1521:  Result := 'The Missing Facet: Droknar''s Light';
    1522:  Result := 'Stopped Clock Tower';
    1523:  Result := 'Convergence: Outer Nayos (Public)';
    1524:  Result := 'Duress: Heitor''s Territory';
    1525:  Result := 'Heitor''s Gate: Heitor''s Territory';
    1526:  Result := 'Inner Nayos';
    1527:  Result := 'Convergence: Outer Nayos (Private Squad)';
    1528:  Result := 'The Survivors: Heitor''s Gate';
    1529:  Result := 'The Survivors: Astral Ward Camp';
    1530:  Result := 'Duress: The Wizard''s Tower';
    1531:  Result := 'Duress: Nayos';
    1532:  Result := 'Forced Hand: Nyedra';
    1533:  Result := 'Eventide''s March: Coliseum of the Midnight King';
    1534:  Result := 'The War Council: Astral Ward Camp';
    1535:  Result := 'Eventide''s March: Nyedra Surrounds';
    1536:  Result := 'Desperate Measures: Forward Bivouac';
    1537:  Result := 'Sovereign of Nayos: The Wizard''s Tower';
    1538:  Result := 'Fractals of the Mists';
    1539:  Result := 'The Eleventh Hour: Citadel of Zakiros';
    1540:  Result := 'Desperate Measures: Forward Bivouac';
    1541:  Result := 'Twice Stricken: Landfall';
    1542:  Result := 'Finding Balance: Hearth''s Glow';
    1543:  Result := 'Titan Research';
    1544:  Result := 'Twice Stricken: Hearth''s Glow';
    1545:  Result := 'Finding Balance: Sanguine Crater';
    1546:  Result := 'Home Sweet Home: Hearth''s Glow';
    1547:  Result := 'Sorrow in These Halls: Harvest Den';
    1549:  Result := 'Missing in Action: Haar Mire';
    1550:  Result := 'Lowland Shore';
    1551:  Result := 'The Tyrian Alliance: Guild Initiative Headquarters';
    1552:  Result := 'Against the Wall: Sulfurous Springs';
    1553:  Result := 'Sorrow in These Halls: The Wizard''s Tower';
    1554:  Result := 'Janthir Syntri';
    1555:  Result := 'Strangers among Lands: Festering Basin';
    1556:  Result := 'Unknown Territory: Moon Camp';
    1557:  Result := 'Home Sweet Home: Abandoned Homestead';
    1558:  Result := 'Hearth''s Glow';
    1559:  Result := 'Against the Wall: Hearth''s Glow';
    1560:  Result := 'Strangers among Lands: Guild Initiative Headquarters';
    1561:  Result := 'Push Prototype�BETA';
    1562:  Result := 'Convergence: Mount Balrior (Private Squad)';
    1563:  Result := 'Trial and Error: The Wizard''s Tower';
    1564:  Result := 'Mount Balrior';
    1565:  Result := 'Battle''s Eve: Harvest Den';
    1567:  Result := 'Balrior Peak: Harvest Den';
    1568:  Result := 'Trial and Error: Janthir Syntri';
    1569:  Result := 'Trial and Error: Durmand Priory';
    1570:  Result := 'Mists Vault';
    1571:  Result := 'Convergence: Mount Balrior (Public)';
    1572:  Result := 'Balrior Peak: Mount Balrior';
    1573:  Result := 'Mabon''s Grief: Bava Nisos Outskirts';
    1574:  Result := 'Bava Nisos';
    1575:  Result := 'Mistburned Barrens';
    1577:  Result := 'A Legacy Damned: The Golden Lake';
    1578:  Result := 'A Legacy Damned: Alliance Staging Ground';
    1579:  Result := 'Into the Valley of Shadow: Valley of Agony';
    1580:  Result := 'Into the Valley of Shadow: Alliance Staging Ground';
    1582:  Result := 'A Titanic Undertaking: Saevus''s Heart';
    1583:  Result := 'Salvation''s Cost: Foundry of Failed Creations';
    1584:  Result := 'Fractals of the Mists';
    1585:  Result := 'Salvation''s Cost: Saevus''s Heart';
    1586:  Result := 'Forced Entry: Bava Nisos Outskirts';
    1587:  Result := 'Forced Entry: Bava Nisos';
    1588:  Result := 'Salvation''s Cost: Guild Initiative Headquarters';
    1589:  Result := 'A Titanic Undertaking: Bava Nisos';
  end;
end;

end.
